// https://www.pro-football-reference.com/teams/cle/2019_roster.htm
// const rows = [...document.querySelector("#games_played_team tbody").querySelectorAll("tr")]
// const players = rows.map((x) => {
//   const name = x.querySelector("[data-stat='player']").innerText
//   const number = parseInt(x.querySelector("[data-stat='uniform_number']").innerHTML, 10)
//   const weight = parseInt(x.querySelector("[data-stat='weight']").innerHTML, 10)
//   const height = x
//     .querySelector("[data-stat='height']")
//     .innerHTML.split("-")
//     .map((x) => parseInt(x, 10))
//     .reduce((acc, cv, ci) => {
//       const inches = ci === 0 ? 12 * cv : cv
//       return inches + acc
//     }, 0)
//   const birthDate = x.querySelector("[data-stat='birth_date_mod']").innerHTML
//   const result = { name, number, weight, height, birthDate }
//   return result
// })
// copy(players)

export default [
  {
    name: "Genard Avery",
    number: 55,
    weight: 250,
    height: 72,
    birthDate: "4/26/1995",
    team: "Browns",
  },
  {
    name: "Odell Beckham",
    number: 13,
    weight: 198,
    height: 71,
    birthDate: "11/5/1992",
    team: "Browns",
  },
  {
    name: "Joel Bitonio",
    number: 75,
    weight: 320,
    height: 76,
    birthDate: "10/11/1991",
    team: "Browns",
  },
  {
    name: "Pharaoh Brown",
    number: 86,
    weight: 258,
    height: 78,
    birthDate: "5/4/1994",
    team: "Browns",
  },
  {
    name: "Morgan Burnett",
    number: 42,
    weight: 210,
    height: 73,
    birthDate: "1/13/1989",
    team: "Browns",
  },
  {
    name: "T.J. Carrie",
    number: 38,
    weight: 204,
    height: 72,
    birthDate: "7/28/1990",
    team: "Browns",
  },
  {
    name: "Nick Chubb",
    number: 24,
    weight: 227,
    height: 71,
    birthDate: "12/27/1995",
    team: "Browns",
  },
  {
    name: "Austin Corbett",
    number: 63,
    weight: 306,
    height: 76,
    birthDate: "9/5/1995",
    team: "Browns",
  },
  {
    name: "Daniel Ekuale",
    number: 96,
    weight: 300,
    height: 75,
    birthDate: "1/13/1994",
    team: "Browns",
  },
  {
    name: "Myles Garrett",
    number: 95,
    weight: 272,
    height: 76,
    birthDate: "12/29/1995",
    team: "Browns",
  },
  {
    name: "Garrett Gilbert",
    number: 3,
    weight: 230,
    height: 76,
    birthDate: "7/1/1991",
    team: "Browns",
  },
  {
    name: "Jamie Gillan",
    number: 7,
    weight: 207,
    height: 73,
    birthDate: "6/4/1997",
    team: "Browns",
  },
  {
    name: "Demetrius Harris",
    number: 88,
    weight: 230,
    height: 79,
    birthDate: "7/29/1991",
    team: "Browns",
  },
  {
    name: "Rashard Higgins",
    number: 81,
    weight: 198,
    height: 73,
    birthDate: "10/7/1994",
    team: "Browns",
  },
  {
    name: "Dontrell Hilliard",
    number: 25,
    weight: 202,
    height: 71,
    birthDate: "2/26/1995",
    team: "Browns",
  },
  {
    name: "Player ",
    number: null,
    weight: null,
    height: null,
    birthDate: "BirthDate",
    team: "Browns",
  },
  {
    name: "KhaDarel Hodge",
    number: 12,
    weight: 205,
    height: 74,
    birthDate: "1/3/1995",
    team: "Browns",
  },
  {
    name: "Chris Hubbard",
    number: 74,
    weight: 295,
    height: 76,
    birthDate: "4/23/1991",
    team: "Browns",
  },
  {
    name: "Charley Hughlett",
    number: 47,
    weight: 248,
    height: 76,
    birthDate: "5/16/1990",
    team: "Browns",
  },
  {
    name: "Malik Jefferson",
    number: 40,
    weight: 241,
    height: 74,
    birthDate: "11/15/1996",
    team: "Browns",
  },
  {
    name: "D'Ernest Johnson",
    number: 30,
    weight: 208,
    height: 70,
    birthDate: "2/27/1996",
    team: "Browns",
  },
  {
    name: "Christian Kirksey",
    number: 58,
    weight: 235,
    height: 74,
    birthDate: "8/31/1992",
    team: "Browns",
  },
  {
    name: "Eric Kush",
    number: 72,
    weight: 317,
    height: 76,
    birthDate: "9/9/1989",
    team: "Browns",
  },
  {
    name: "Kendall Lamm",
    number: 70,
    weight: 310,
    height: 77,
    birthDate: "6/5/1992",
    team: "Browns",
  },
  {
    name: "Jarvis Landry",
    number: 80,
    weight: 196,
    height: 71,
    birthDate: "11/28/1992",
    team: "Browns",
  },
  {
    name: "Devaroe Lawrence",
    number: 99,
    weight: 295,
    height: 74,
    birthDate: "10/13/1992",
    team: "Browns",
  },
  {
    name: "Baker Mayfield",
    number: 6,
    weight: 215,
    height: 73,
    birthDate: "4/14/1995",
    team: "Browns",
  },
  {
    name: "Justin McCray",
    number: 67,
    weight: 317,
    height: 75,
    birthDate: "5/31/1992",
    team: "Browns",
  },
  {
    name: "Elijah McGuire",
    number: 36,
    weight: 214,
    height: 70,
    birthDate: "6/1/1994",
    team: "Browns",
  },
  {
    name: "Terrance Mitchell",
    number: 39,
    weight: 191,
    height: 71,
    birthDate: "5/17/1992",
    team: "Browns",
  },
  {
    name: "Eric Murray",
    number: 22,
    weight: 199,
    height: 71,
    birthDate: "1/7/1994",
    team: "Browns",
  },
  {
    name: "Player ",
    number: null,
    weight: null,
    height: null,
    birthDate: "BirthDate",
    team: "Browns",
  },
  {
    name: "David Njoku",
    number: 85,
    weight: 246,
    height: 76,
    birthDate: "7/10/1996",
    team: "Browns",
  },
  {
    name: "Larry Ogunjobi",
    number: 65,
    weight: 305,
    height: 75,
    birthDate: "6/3/1994",
    team: "Browns",
  },
  {
    name: "Damarious Randall",
    number: 23,
    weight: 196,
    height: 71,
    birthDate: "8/29/1992",
    team: "Browns",
  },
  {
    name: "Damion Ratley",
    number: 18,
    weight: 200,
    height: 74,
    birthDate: "4/16/1995",
    team: "Browns",
  },
  {
    name: "Sheldrick Redwine",
    number: 29,
    weight: 196,
    height: 72,
    birthDate: "11/6/1996",
    team: "Browns",
  },
  {
    name: "Sheldon Richardson",
    number: 98,
    weight: 294,
    height: 75,
    birthDate: "11/29/1990",
    team: "Browns",
  },
  {
    name: "Greg Robinson",
    number: 78,
    weight: 330,
    height: 77,
    birthDate: "10/21/1992",
    team: "Browns",
  },
  {
    name: "Joe Schobert",
    number: 53,
    weight: 245,
    height: 73,
    birthDate: "11/6/1993",
    team: "Browns",
  },
  {
    name: "Ricky Seals-Jones",
    number: 83,
    weight: 243,
    height: 77,
    birthDate: "3/15/1995",
    team: "Browns",
  },
  {
    name: "Austin Seibert",
    number: 4,
    weight: 214,
    height: 69,
    birthDate: "11/15/1996",
    team: "Browns",
  },
  {
    name: "Chris Smith",
    number: 50,
    weight: 266,
    height: 73,
    birthDate: "2/11/1992",
    team: "Browns",
  },
  {
    name: "Sione Takitaki",
    number: 44,
    weight: 238,
    height: 73,
    birthDate: "6/8/1995",
    team: "Browns",
  },
  {
    name: "Adarius Taylor",
    number: 57,
    weight: 230,
    height: 72,
    birthDate: "9/21/1990",
    team: "Browns",
  },
  {
    name: "Taywan Taylor",
    number: 10,
    weight: 203,
    height: 71,
    birthDate: "3/2/1995",
    team: "Browns",
  },
  {
    name: "Wyatt Teller",
    number: 77,
    weight: 314,
    height: 76,
    birthDate: "11/21/1994",
    team: "Browns",
  },
  {
    name: "Player ",
    number: null,
    weight: null,
    height: null,
    birthDate: "BirthDate",
    team: "Browns",
  },
  {
    name: "Chad Thomas",
    number: 92,
    weight: 278,
    height: 77,
    birthDate: "10/12/1995",
    team: "Browns",
  },
  {
    name: "Tavierre Thomas",
    number: 20,
    weight: 205,
    height: 70,
    birthDate: "3/11/1996",
    team: "Browns",
  },
  {
    name: "J.C. Tretter",
    number: 64,
    weight: 307,
    height: 76,
    birthDate: "2/12/1991",
    team: "Browns",
  },
  {
    name: "Olivier Vernon",
    number: 54,
    weight: 262,
    height: 74,
    birthDate: "10/7/1990",
    team: "Browns",
  },
  {
    name: "Denzel Ward",
    number: 21,
    weight: 190,
    height: 71,
    birthDate: "4/28/1997",
    team: "Browns",
  },
  {
    name: "Jermaine Whitehead",
    number: 35,
    weight: 195,
    height: 71,
    birthDate: "3/12/1993",
    team: "Browns",
  },
  {
    name: "Greedy Williams",
    number: 26,
    weight: 185,
    height: 74,
    birthDate: "12/3/1997",
    team: "Browns",
  },
  {
    name: "Mack Wilson",
    number: 51,
    weight: 240,
    height: 73,
    birthDate: "2/14/1998",
    team: "Browns",
  },
]
